services:
    guzzle.client:
        class: GuzzleHttp\Client

    # -------  clients

    app.client.bitstamp:
        class: AppBundle\Service\Client\BitstampClient
        arguments:
            - '@guzzle.client'
            - '%client.bitstamp%'

    app.client.itbit:
        class: AppBundle\Service\Client\ItbitClient
        arguments:
            - '@guzzle.client'
            - '%client.itbit%'

    app.client.kraken:
        class: AppBundle\Service\Client\KrakenClient
        arguments:
            - '@guzzle.client'
            - '%client.kraken%'

    app.client.okcoin:
        class: AppBundle\Service\Client\OkcoinClient
        arguments:
            - '@guzzle.client'
            - '%client.okcoin%'

    app.client.binance:
        class: AppBundle\Service\Client\BinanceClient
        arguments:
            - '@guzzle.client'
            - '%client.binance%'

    app.client.cexio:
        class: AppBundle\Service\Client\CexioClient
        arguments:
            - '@guzzle.client'
            - '%client.cexio%'

    # -------  services

    app.bitstamp.service:
        class: AppBundle\Service\BitstampService
        arguments:
            - '@app.client.bitstamp'

    app.itbit.service:
        class: AppBundle\Service\ItbitService
        arguments:
            - '@app.client.itbit'

    app.kraken.service:
        class: AppBundle\Service\KrakenService
        arguments:
            - '@app.client.kraken'

    app.okcoin.service:
        class: AppBundle\Service\OkcoinService
        arguments:
            - '@app.client.okcoin'

    app.binance.service:
        class: AppBundle\Service\BinanceService
        arguments:
            - '@app.client.binance'

    app.cexio.service:
        class: AppBundle\Service\CexioService
        arguments:
            - '@app.client.cexio'

    app.ticker.service:
        class: AppBundle\Service\TickerService
        arguments:
            - { bitstamp: '@app.bitstamp.service', itbit: '@app.itbit.service',  kraken: '@app.kraken.service', okcoin: '@app.okcoin.service', binance: '@app.binance.service', cexio: '@app.cexio.service'}

    app.balance.service:
        class: AppBundle\Service\BalanceService
        arguments:
            - { bitstamp: '@app.bitstamp.service', itbit: '@app.itbit.service',  kraken: '@app.kraken.service', okcoin: '@app.okcoin.service', binance: '@app.binance.service', cexio: '@app.cexio.service'}

    # -------  services

    app.ticker.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Ticker

    app.balance.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Balance

    app.status.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Status