services:
    guzzle.client:
        class: GuzzleHttp\Client

    # -------  clients

    app.client.bitstamp:
        class: AppBundle\Service\Client\BitstampClient
        arguments:
            - '@guzzle.client'
            - '%client.bitstamp%'

    app.client.itbit:
        class: AppBundle\Service\Client\ItbitClient
        arguments:
            - '@guzzle.client'
            - '%client.itbit%'

    app.client.kraken:
        class: AppBundle\Service\Client\KrakenClient
        arguments:
            - '@guzzle.client'
            - '%client.kraken%'

    # -------  services

    app.bitstamp.service:
        class: AppBundle\Service\BitstampService
        arguments:
            - '@app.client.bitstamp'

    app.itbit.service:
        class: AppBundle\Service\ItbitService
        arguments:
            - '@app.client.itbit'

    app.kraken.service:
        class: AppBundle\Service\KrakenService
        arguments:
            - '@app.client.kraken'

    app.ticker.service:
        class: AppBundle\Service\TickerService
        arguments:
            - { bitstamp: '@app.bitstamp.service', itbit: '@app.itbit.service',  kraken: '@app.kraken.service'}

    # -------  services

    app.ticker.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Ticker